# Generated by Django 4.1.1 on 2022-10-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_skill_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_level',
            field=models.IntegerField(choices=[(1, '1 - Fundamental Awareness'), (2, '2 - Novice'), (3, '3 - Intermediate'), (4, '4 - Advanced'), (5, '5 - Expert')], default=1, max_length=1),
        ),
    ]
